// src/constants/roles.js

module.exports = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  FINANCE_ADMIN: 'FINANCE_ADMIN',
  FRAUD_ADMIN: 'FRAUD_ADMIN',
  ANALYTICS_ADMIN: 'ANALYTICS_ADMIN',
  SUPPORT_ADMIN: 'SUPPORT_ADMIN'
};
